# Installation

Downloading a small SpaCy model as a backbone

In [1]:
!python -m spacy download en_core_web_sm

Collecting en-core-web-sm==3.8.0
  Downloading en_core_web_sm-3.8.0-py3-none-any.whl (12.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 12.8/12.8 MB 93.2 MB/s  0:00:00
✔ Download and installation successful
You can now load the package via spacy.load('en_core_web_sm')

Downloading wn for semantic features

In [2]:
!python -m wn download omw-en31:1.4

Download [##############################] (10780108/10780108 bytes) Completeg
Read [##############################] (1223246/1223246) n/T/tmpazwd1vrq/omw-en31/omw-en31.xmll
Added omw-en31:1.4 (OMW English Wordnet based on WordNet 3.1)plesonsionssurs

"Manually" download the NRC lexicons and put them in the location where elfen is, in a folder called `elfen_resources`

We first get the location of the elfen package:

In [3]:
!pip show elfen

Name: elfen
Version: 1.3.1
Summary: ELFEN - Efficient Linguistic Feature Extraction for Natural Language Datasets
Home-page: https://github.com/mmmaurer/elfen
Author:
Author-email: Maximilian Maurer <mmmaurer@pm.me>
License:
Location: /Users/maximilianmaurer/Projects/elfen-tutorials/.venv/lib/python3.12/site-packages
Requires: fastexcel, numpy, polars, pyarrow, Requests, scipy, spacy, spacy-transformers, spacy_syllables, stanza, wn
Required-by:

Create the subfolder

In [ ]:
!mkdir CHANGE/TO/LOCATION/elfen_resources

Download the first NRC lexicon

In [ ]:
!curl -o /CHANGE/TO/LOCATION/elfen_resources/NRC-Emotion-Intensity-Lexicon.zip https://saifmohammad.com/WebDocs/Lexicons/NRC-Emotion-Intensity-Lexicon.zip

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 28.2M  100 28.2M    0     0  5585k      0  0:00:05  0:00:05 --:--:-- 6044k

Create the correct subfolder structure

In [ ]:
!mkdir CHANGE/TO/LOCATION/elfen_resources/Emotion
!mkdir CHANGE/TO/LOCATION/elfen_resources/Emotion/Intensity

mkdir: /Users/maximilianmaurer/Projects/elfen-tutorials/.venv/lib/python3.12/site-packages/elfen_resources/Emotion: File exists

Move the zipped lexicon

In [ ]:
!mv CHANGE/TO/LOCATION/elfen_resources/NRC-Emotion-Intensity-Lexicon.zip CHANGE/TO/LOCATION/elfen_resources/Emotion/Intensity/NRC-Emotion-Intensity-Lexicon.zip

Unzip the file

In [ ]:
!unzip /CHANGE/TO/LOCATION/elfen_resources/Emotion/Intensity/NRC-Emotion-Intensity-Lexicon.zip -d /CHANGE/TO/LOCATION/elfen_resources/Emotion/Intensity/

Archive:  /Users/maximilianmaurer/Projects/elfen-tutorials/.venv/lib/python3.12/site-packages/elfen_resources/Emotion/Intensity/NRC-Emotion-Intensity-Lexicon.zip
   creating: /Users/maximilianmaurer/Projects/elfen-tutorials/.venv/lib/python3.12/site-packages/elfen_resources/Emotion/Intensity//NRC-Emotion-Intensity-Lexicon
  inflating: /Users/maximilianmaurer/Projects/elfen-tutorials/.venv/lib/python3.12/site-packages/elfen_resources/Emotion/Intensity//NRC-Emotion-Intensity-Lexicon/NRC-Emotion-Intensity-Lexicon-v1-ForVariousLanguages-withZeroIntensityEntries.txt
  inflating: /Users/maximilianmaurer/Projects/elfen-tutorials/.venv/lib/python3.12/site-packages/elfen_resources/Emotion/Intensity//NRC-Emotion-Intensity-Lexicon/.DS_Store
  inflating: /Users/maximilianmaurer/Projects/elfen-tutorials/.venv/lib/python3.12/site-packages/elfen_resources/Emotion/Intensity//__MACOSX/NRC-Emotion-Intensity-Lexicon/._.DS_Store
  inflating: /Users/maximilianmaurer/Projects/elfen-tutorials/.venv/lib/python3.12/site-packages/elfen_resources/Emotion/Intensity//NRC-Emotion-Intensity-Lexicon/Paper-Practical-Ethical-Considerations-Lexicons.pdf
  inflating: /Users/maximilianmaurer/Projects/elfen-tutorials/.venv/lib/python3.12/site-packages/elfen_resources/Emotion/Intensity//__MACOSX/NRC-Emotion-Intensity-Lexicon/._Paper-Practical-Ethical-Considerations-Lexicons.pdf
  inflating: /Users/maximilianmaurer/Projects/elfen-tutorials/.venv/lib/python3.12/site-packages/elfen_resources/Emotion/Intensity//NRC-Emotion-Intensity-Lexicon/NRC-Emotion-Intensity-Lexicon-v1-ForVariousLanguages.txt
  inflating: /Users/maximilianmaurer/Projects/elfen-tutorials/.venv/lib/python3.12/site-packages/elfen_resources/Emotion/Intensity//NRC-Emotion-Intensity-Lexicon/NRC-Emotion-Intensity-Lexicon-v1.txt
  inflating: /Users/maximilianmaurer/Projects/elfen-tutorials/.venv/lib/python3.12/site-packages/elfen_resources/Emotion/Intensity//NRC-Emotion-Intensity-Lexicon/README.txt
  inflating: /Users/maximilianmaurer/Projects/elfen-tutorials/.venv/lib/python3.12/site-packages/elfen_resources/Emotion/Intensity//NRC-Emotion-Intensity-Lexicon/Paper-Ethics-Sheet-Emotion-Recognition.pdf
  inflating: /Users/maximilianmaurer/Projects/elfen-tutorials/.venv/lib/python3.12/site-packages/elfen_resources/Emotion/Intensity//__MACOSX/NRC-Emotion-Intensity-Lexicon/._Paper-Ethics-Sheet-Emotion-Recognition.pdf
  inflating: /Users/maximilianmaurer/Projects/elfen-tutorials/.venv/lib/python3.12/site-packages/elfen_resources/Emotion/Intensity//NRC-Emotion-Intensity-Lexicon/Paper-lrec2018-word-emotion.pdf
  inflating: /Users/maximilianmaurer/Projects/elfen-tutorials/.venv/lib/python3.12/site-packages/elfen_resources/Emotion/Intensity//__MACOSX/NRC-Emotion-Intensity-Lexicon/._Paper-lrec2018-word-emotion.pdf
   creating: /Users/maximilianmaurer/Projects/elfen-tutorials/.venv/lib/python3.12/site-packages/elfen_resources/Emotion/Intensity//NRC-Emotion-Intensity-Lexicon/OneFilePerLanguage
  inflating: /Users/maximilianmaurer/Projects/elfen-tutorials/.venv/lib/python3.12/site-packages/elfen_resources/Emotion/Intensity//NRC-Emotion-Intensity-Lexicon/ListOfLanguages-For-Which-Lexicon-Availabale.txt
   creating: /Users/maximilianmaurer/Projects/elfen-tutorials/.venv/lib/python3.12/site-packages/elfen_resources/Emotion/Intensity//NRC-Emotion-Intensity-Lexicon/OneFilePerEmotion
  inflating: /Users/maximilianmaurer/Projects/elfen-tutorials/.venv/lib/python3.12/site-packages/elfen_resources/Emotion/Intensity//NRC-Emotion-Intensity-Lexicon/OneFilePerLanguage/Swahili-NRC-Emotion-Intensity-Lexicon-v1.txt
  inflating: /Users/maximilianmaurer/Projects/elfen-tutorials/.venv/lib/python3.12/site-packages/elfen_resources/Emotion/Intensity//NRC-Emotion-Intensity-Lexicon/OneFilePerLanguage/Cebuano-NRC-Emotion-Intensity-Lexicon-v1.txt
  inflating: /Users/maximilianmaurer/Projects/elfen-tutorials/.venv/lib/python3.12/site-packages/elfen_resources/Emotion/Intensity//NRC-Emotion-Intensity-Lexicon/OneFilePerLanguage/Ukrainian-NRC-Emotion-Intensity-Lexicon-v1.txt
  inflating: /Users/maximilianmaurer/Projects/elfen-tutorials/.venv/lib/python3.12/site-packages/elfen_resources/Emotion/Intensity//NRC-Emotion-Intensity-Lexicon/OneFilePerLanguage/German-NRC-Emotion-Intensity-Lexicon-v1.txt
  inflating: /Users/maximilianmaurer/Projects/elfen-tutorials/.venv/lib/python3.12/site-packages/elfen_resources/Emotion/Intensity//NRC-Emotion-Intensity-Lexicon/OneFilePerLanguage/Russian-NRC-Emotion-Intensity-Lexicon-v1.txt
  inflating: /Users/maximilianmaurer/Projects/elfen-tutorials/.venv/lib/python3.12/site-packages/elfen_resources/Emotion/Intensity//NRC-Emotion-Intensity-Lexicon/OneFilePerLanguage/Swedish-NRC-Emotion-Intensity-Lexicon-v1.txt
  inflating: /Users/maximilianmaurer/Projects/elfen-tutorials/.venv/lib/python3.12/site-packages/elfen_resources/Emotion/Intensity//NRC-Emotion-Intensity-Lexicon/OneFilePerLanguage/Haitian-Creole-NRC-Emotion-Intensity-Lexicon-v1.txt
  inflating: /Users/maximilianmaurer/Projects/elfen-tutorials/.venv/lib/python3.12/site-packages/elfen_resources/Emotion/Intensity//NRC-Emotion-Intensity-Lexicon/OneFilePerLanguage/Arabic-NRC-Emotion-Intensity-Lexicon-v1.txt
  inflating: /Users/maximilianmaurer/Projects/elfen-tutorials/.venv/lib/python3.12/site-packages/elfen_resources/Emotion/Intensity//NRC-Emotion-Intensity-Lexicon/OneFilePerLanguage/Welsh-NRC-Emotion-Intensity-Lexicon-v1.txt
  inflating: /Users/maximilianmaurer/Projects/elfen-tutorials/.venv/lib/python3.12/site-packages/elfen_resources/Emotion/Intensity//NRC-Emotion-Intensity-Lexicon/OneFilePerLanguage/Maltese-NRC-Emotion-Intensity-Lexicon-v1.txt
  inflating: /Users/maximilianmaurer/Projects/elfen-tutorials/.venv/lib/python3.12/site-packages/elfen_resources/Emotion/Intensity//NRC-Emotion-Intensity-Lexicon/OneFilePerLanguage/Urdu-NRC-Emotion-Intensity-Lexicon-v1.txt
  inflating: /Users/maximilianmaurer/Projects/elfen-tutorials/.venv/lib/python3.12/site-packages/elfen_resources/Emotion/Intensity//NRC-Emotion-Intensity-Lexicon/OneFilePerLanguage/Yiddish-NRC-Emotion-Intensity-Lexicon-v1.txt
  inflating: /Users/maximilianmaurer/Projects/elfen-tutorials/.venv/lib/python3.12/site-packages/elfen_resources/Emotion/Intensity//NRC-Emotion-Intensity-Lexicon/OneFilePerLanguage/Romanian-NRC-Emotion-Intensity-Lexicon-v1.txt
  inflating: /Users/maximilianmaurer/Projects/elfen-tutorials/.venv/lib/python3.12/site-packages/elfen_resources/Emotion/Intensity//NRC-Emotion-Intensity-Lexicon/OneFilePerLanguage/Marathi-NRC-Emotion-Intensity-Lexicon-v1.txt
  inflating: /Users/maximilianmaurer/Projects/elfen-tutorials/.venv/lib/python3.12/site-packages/elfen_resources/Emotion/Intensity//NRC-Emotion-Intensity-Lexicon/OneFilePerLanguage/Serbian-NRC-Emotion-Intensity-Lexicon-v1.txt
  inflating: /Users/maximilianmaurer/Projects/elfen-tutorials/.venv/lib/python3.12/site-packages/elfen_resources/Emotion/Intensity//NRC-Emotion-Intensity-Lexicon/OneFilePerLanguage/Bulgarian-NRC-Emotion-Intensity-Lexicon-v1.txt
  inflating: /Users/maximilianmaurer/Projects/elfen-tutorials/.venv/lib/python3.12/site-packages/elfen_resources/Emotion/Intensity//NRC-Emotion-Intensity-Lexicon/OneFilePerLanguage/Esperanto-NRC-Emotion-Intensity-Lexicon-v1.txt
  inflating: /Users/maximilianmaurer/Projects/elfen-tutorials/.venv/lib/python3.12/site-packages/elfen_resources/Emotion/Intensity//NRC-Emotion-Intensity-Lexicon/OneFilePerLanguage/Scots-Gaelic-NRC-Emotion-Intensity-Lexicon-v1.txt
  inflating: /Users/maximilianmaurer/Projects/elfen-tutorials/.venv/lib/python3.12/site-packages/elfen_resources/Emotion/Intensity//NRC-Emotion-Intensity-Lexicon/OneFilePerLanguage/Lao-NRC-Emotion-Intensity-Lexicon-v1.txt
  inflating: /Users/maximilianmaurer/Projects/elfen-tutorials/.venv/lib/python3.12/site-packages/elfen_resources/Emotion/Intensity//NRC-Emotion-Intensity-Lexicon/OneFilePerLanguage/Uzbek-NRC-Emotion-Intensity-Lexicon-v1.txt
  inflating: /Users/maximilianmaurer/Projects/elfen-tutorials/.venv/lib/python3.12/site-packages/elfen_resources/Emotion/Intensity//NRC-Emotion-Intensity-Lexicon/OneFilePerLanguage/Macedonian-NRC-Emotion-Intensity-Lexicon-v1.txt
  inflating: /Users/maximilianmaurer/Projects/elfen-tutorials/.venv/lib/python3.12/site-packages/elfen_resources/Emotion/Intensity//NRC-Emotion-Intensity-Lexicon/OneFilePerLanguage/Latvian-NRC-Emotion-Intensity-Lexicon-v1.txt
  inflating: /Users/maximilianmaurer/Projects/elfen-tutorials/.venv/lib/python3.12/site-packages/elfen_resources/Emotion/Intensity//NRC-Emotion-Intensity-Lexicon/OneFilePerLanguage/Tamil-NRC-Emotion-Intensity-Lexicon-v1.txt
  inflating: /Users/maximilianmaurer/Projects/elfen-tutorials/.venv/lib/python3.12/site-packages/elfen_resources/Emotion/Intensity//NRC-Emotion-Intensity-Lexicon/OneFilePerLanguage/Filipino-NRC-Emotion-Intensity-Lexicon-v1.txt
  inflating: /Users/maximilianmaurer/Projects/elfen-tutorials/.venv/lib/python3.12/site-packages/elfen_resources/Emotion/Intensity//NRC-Emotion-Intensity-Lexicon/OneFilePerLanguage/Uyghur-NRC-Emotion-Intensity-Lexicon-v1.txt
  inflating: /Users/maximilianmaurer/Projects/elfen-tutorials/.venv/lib/python3.12/site-packages/elfen_resources/Emotion/Intensity//NRC-Emotion-Intensity-Lexicon/OneFilePerLanguage/Galician-NRC-Emotion-Intensity-Lexicon-v1.txt
  inflating: /Users/maximilianmaurer/Projects/elfen-tutorials/.venv/lib/python3.12/site-packages/elfen_resources/Emotion/Intensity//NRC-Emotion-Intensity-Lexicon/OneFilePerLanguage/Estonian-NRC-Emotion-Intensity-Lexicon-v1.txt
  inflating: /Users/maximilianmaurer/Projects/elfen-tutorials/.venv/lib/python3.12/site-packages/elfen_resources/Emotion/Intensity//NRC-Emotion-Intensity-Lexicon/OneFilePerLanguage/Indonesian-NRC-Emotion-Intensity-Lexicon-v1.txt
  inflating: /Users/maximilianmaurer/Projects/elfen-tutorials/.venv/lib/python3.12/site-packages/elfen_resources/Emotion/Intensity//NRC-Emotion-Intensity-Lexicon/OneFilePerLanguage/Czech-NRC-Emotion-Intensity-Lexicon-v1.txt
  inflating: /Users/maximilianmaurer/Projects/elfen-tutorials/.venv/lib/python3.12/site-packages/elfen_resources/Emotion/Intensity//NRC-Emotion-Intensity-Lexicon/OneFilePerLanguage/Malayalam-NRC-Emotion-Intensity-Lexicon-v1.txt
  inflating: /Users/maximilianmaurer/Projects/elfen-tutorials/.venv/lib/python3.12/site-packages/elfen_resources/Emotion/Intensity//NRC-Emotion-Intensity-Lexicon/OneFilePerLanguage/Polish-NRC-Emotion-Intensity-Lexicon-v1.txt
  inflating: /Users/maximilianmaurer/Projects/elfen-tutorials/.venv/lib/python3.12/site-packages/elfen_resources/Emotion/Intensity//NRC-Emotion-Intensity-Lexicon/OneFilePerLanguage/Chinese-Simplified-NRC-Emotion-Intensity-Lexicon-v1.txt
  inflating: /Users/maximilianmaurer/Projects/elfen-tutorials/.venv/lib/python3.12/site-packages/elfen_resources/Emotion/Intensity//NRC-Emotion-Intensity-Lexicon/OneFilePerLanguage/Bengali-NRC-Emotion-Intensity-Lexicon-v1.txt
  inflating: /Users/maximilianmaurer/Projects/elfen-tutorials/.venv/lib/python3.12/site-packages/elfen_resources/Emotion/Intensity//NRC-Emotion-Intensity-Lexicon/OneFilePerLanguage/Kinyarwanda-NRC-Emotion-Intensity-Lexicon-v1.txt
  inflating: /Users/maximilianmaurer/Projects/elfen-tutorials/.venv/lib/python3.12/site-packages/elfen_resources/Emotion/Intensity//NRC-Emotion-Intensity-Lexicon/OneFilePerLanguage/Hmong-NRC-Emotion-Intensity-Lexicon-v1.txt
  inflating: /Users/maximilianmaurer/Projects/elfen-tutorials/.venv/lib/python3.12/site-packages/elfen_resources/Emotion/Intensity//NRC-Emotion-Intensity-Lexicon/OneFilePerLanguage/Luxembourgish-NRC-Emotion-Intensity-Lexicon-v1.txt
  inflating: /Users/maximilianmaurer/Projects/elfen-tutorials/.venv/lib/python3.12/site-packages/elfen_resources/Emotion/Intensity//NRC-Emotion-Intensity-Lexicon/OneFilePerLanguage/Gujarati-NRC-Emotion-Intensity-Lexicon-v1.txt
  inflating: /Users/maximilianmaurer/Projects/elfen-tutorials/.venv/lib/python3.12/site-packages/elfen_resources/Emotion/Intensity//NRC-Emotion-Intensity-Lexicon/OneFilePerLanguage/Persian-NRC-Emotion-Intensity-Lexicon-v1.txt
  inflating: /Users/maximilianmaurer/Projects/elfen-tutorials/.venv/lib/python3.12/site-packages/elfen_resources/Emotion/Intensity//NRC-Emotion-Intensity-Lexicon/OneFilePerLanguage/Javanese-NRC-Emotion-Intensity-Lexicon-v1.txt
  inflating: /Users/maximilianmaurer/Projects/elfen-tutorials/.venv/lib/python3.12/site-packages/elfen_resources/Emotion/Intensity//NRC-Emotion-Intensity-Lexicon/OneFilePerLanguage/Spanish-NRC-Emotion-Intensity-Lexicon-v1.txt
  inflating: /Users/maximilianmaurer/Projects/elfen-tutorials/.venv/lib/python3.12/site-packages/elfen_resources/Emotion/Intensity//NRC-Emotion-Intensity-Lexicon/OneFilePerLanguage/Somali-NRC-Emotion-Intensity-Lexicon-v1.txt
  inflating: /Users/maximilianmaurer/Projects/elfen-tutorials/.venv/lib/python3.12/site-packages/elfen_resources/Emotion/Intensity//NRC-Emotion-Intensity-Lexicon/OneFilePerLanguage/Zulu-NRC-Emotion-Intensity-Lexicon-v1.txt
  inflating: /Users/maximilianmaurer/Projects/elfen-tutorials/.venv/lib/python3.12/site-packages/elfen_resources/Emotion/Intensity//NRC-Emotion-Intensity-Lexicon/OneFilePerLanguage/Hebrew-NRC-Emotion-Intensity-Lexicon-v1.txt
  inflating: /Users/maximilianmaurer/Projects/elfen-tutorials/.venv/lib/python3.12/site-packages/elfen_resources/Emotion/Intensity//NRC-Emotion-Intensity-Lexicon/OneFilePerLanguage/Malagasy-NRC-Emotion-Intensity-Lexicon-v1.txt
  inflating: /Users/maximilianmaurer/Projects/elfen-tutorials/.venv/lib/python3.12/site-packages/elfen_resources/Emotion/Intensity//NRC-Emotion-Intensity-Lexicon/OneFilePerLanguage/Kazakh-NRC-Emotion-Intensity-Lexicon-v1.txt
  inflating: /Users/maximilianmaurer/Projects/elfen-tutorials/.venv/lib/python3.12/site-packages/elfen_resources/Emotion/Intensity//NRC-Emotion-Intensity-Lexicon/OneFilePerLanguage/Mongolian-NRC-Emotion-Intensity-Lexicon-v1.txt
  inflating: /Users/maximilianmaurer/Projects/elfen-tutorials/.venv/lib/python3.12/site-packages/elfen_resources/Emotion/Intensity//NRC-Emotion-Intensity-Lexicon/OneFilePerLanguage/Vietnamese-NRC-Emotion-Intensity-Lexicon-v1.txt
  inflating: /Users/maximilianmaurer/Projects/elfen-tutorials/.venv/lib/python3.12/site-packages/elfen_resources/Emotion/Intensity//NRC-Emotion-Intensity-Lexicon/OneFilePerLanguage/Telugu-NRC-Emotion-Intensity-Lexicon-v1.txt
  inflating: /Users/maximilianmaurer/Projects/elfen-tutorials/.venv/lib/python3.12/site-packages/elfen_resources/Emotion/Intensity//NRC-Emotion-Intensity-Lexicon/OneFilePerLanguage/Hungarian-NRC-Emotion-Intensity-Lexicon-v1.txt
  inflating: /Users/maximilianmaurer/Projects/elfen-tutorials/.venv/lib/python3.12/site-packages/elfen_resources/Emotion/Intensity//NRC-Emotion-Intensity-Lexicon/OneFilePerLanguage/Hawaiian-NRC-Emotion-Intensity-Lexicon-v1.txt
  inflating: /Users/maximilianmaurer/Projects/elfen-tutorials/.venv/lib/python3.12/site-packages/elfen_resources/Emotion/Intensity//NRC-Emotion-Intensity-Lexicon/OneFilePerLanguage/Maori-NRC-Emotion-Intensity-Lexicon-v1.txt
  inflating: /Users/maximilianmaurer/Projects/elfen-tutorials/.venv/lib/python3.12/site-packages/elfen_resources/Emotion/Intensity//NRC-Emotion-Intensity-Lexicon/OneFilePerLanguage/Sesotho-NRC-Emotion-Intensity-Lexicon-v1.txt
  inflating: /Users/maximilianmaurer/Projects/elfen-tutorials/.venv/lib/python3.12/site-packages/elfen_resources/Emotion/Intensity//NRC-Emotion-Intensity-Lexicon/OneFilePerLanguage/Slovak-NRC-Emotion-Intensity-Lexicon-v1.txt
  inflating: /Users/maximilianmaurer/Projects/elfen-tutorials/.venv/lib/python3.12/site-packages/elfen_resources/Emotion/Intensity//NRC-Emotion-Intensity-Lexicon/OneFilePerLanguage/Irish-NRC-Emotion-Intensity-Lexicon-v1.txt
  inflating: /Users/maximilianmaurer/Projects/elfen-tutorials/.venv/lib/python3.12/site-packages/elfen_resources/Emotion/Intensity//NRC-Emotion-Intensity-Lexicon/OneFilePerLanguage/Amharic-NRC-Emotion-Intensity-Lexicon-v1.txt
  inflating: /Users/maximilianmaurer/Projects/elfen-tutorials/.venv/lib/python3.12/site-packages/elfen_resources/Emotion/Intensity//NRC-Emotion-Intensity-Lexicon/OneFilePerLanguage/Japanese-NRC-Emotion-Intensity-Lexicon-v1.txt
  inflating: /Users/maximilianmaurer/Projects/elfen-tutorials/.venv/lib/python3.12/site-packages/elfen_resources/Emotion/Intensity//NRC-Emotion-Intensity-Lexicon/OneFilePerLanguage/Pashto-NRC-Emotion-Intensity-Lexicon-v1.txt
  inflating: /Users/maximilianmaurer/Projects/elfen-tutorials/.venv/lib/python3.12/site-packages/elfen_resources/Emotion/Intensity//NRC-Emotion-Intensity-Lexicon/OneFilePerLanguage/Frisian-NRC-Emotion-Intensity-Lexicon-v1.txt
  inflating: /Users/maximilianmaurer/Projects/elfen-tutorials/.venv/lib/python3.12/site-packages/elfen_resources/Emotion/Intensity//NRC-Emotion-Intensity-Lexicon/OneFilePerLanguage/Dutch-NRC-Emotion-Intensity-Lexicon-v1.txt
  inflating: /Users/maximilianmaurer/Projects/elfen-tutorials/.venv/lib/python3.12/site-packages/elfen_resources/Emotion/Intensity//NRC-Emotion-Intensity-Lexicon/OneFilePerLanguage/Sindhi-NRC-Emotion-Intensity-Lexicon-v1.txt
  inflating: /Users/maximilianmaurer/Projects/elfen-tutorials/.venv/lib/python3.12/site-packages/elfen_resources/Emotion/Intensity//NRC-Emotion-Intensity-Lexicon/OneFilePerLanguage/Croatian-NRC-Emotion-Intensity-Lexicon-v1.txt
  inflating: /Users/maximilianmaurer/Projects/elfen-tutorials/.venv/lib/python3.12/site-packages/elfen_resources/Emotion/Intensity//NRC-Emotion-Intensity-Lexicon/OneFilePerLanguage/Finnish-NRC-Emotion-Intensity-Lexicon-v1.txt
  inflating: /Users/maximilianmaurer/Projects/elfen-tutorials/.venv/lib/python3.12/site-packages/elfen_resources/Emotion/Intensity//NRC-Emotion-Intensity-Lexicon/OneFilePerLanguage/Lithuanian-NRC-Emotion-Intensity-Lexicon-v1.txt
  inflating: /Users/maximilianmaurer/Projects/elfen-tutorials/.venv/lib/python3.12/site-packages/elfen_resources/Emotion/Intensity//NRC-Emotion-Intensity-Lexicon/OneFilePerLanguage/Turkish-NRC-Emotion-Intensity-Lexicon-v1.txt
  inflating: /Users/maximilianmaurer/Projects/elfen-tutorials/.venv/lib/python3.12/site-packages/elfen_resources/Emotion/Intensity//NRC-Emotion-Intensity-Lexicon/OneFilePerLanguage/Portuguese-NRC-Emotion-Intensity-Lexicon-v1.txt
  inflating: /Users/maximilianmaurer/Projects/elfen-tutorials/.venv/lib/python3.12/site-packages/elfen_resources/Emotion/Intensity//NRC-Emotion-Intensity-Lexicon/OneFilePerLanguage/Yoruba-NRC-Emotion-Intensity-Lexicon-v1.txt
  inflating: /Users/maximilianmaurer/Projects/elfen-tutorials/.venv/lib/python3.12/site-packages/elfen_resources/Emotion/Intensity//NRC-Emotion-Intensity-Lexicon/OneFilePerLanguage/Korean-NRC-Emotion-Intensity-Lexicon-v1.txt
  inflating: /Users/maximilianmaurer/Projects/elfen-tutorials/.venv/lib/python3.12/site-packages/elfen_resources/Emotion/Intensity//NRC-Emotion-Intensity-Lexicon/OneFilePerLanguage/Armenian-NRC-Emotion-Intensity-Lexicon-v1.txt
  inflating: /Users/maximilianmaurer/Projects/elfen-tutorials/.venv/lib/python3.12/site-packages/elfen_resources/Emotion/Intensity//NRC-Emotion-Intensity-Lexicon/OneFilePerLanguage/Chichewa-NRC-Emotion-Intensity-Lexicon-v1.txt
  inflating: /Users/maximilianmaurer/Projects/elfen-tutorials/.venv/lib/python3.12/site-packages/elfen_resources/Emotion/Intensity//NRC-Emotion-Intensity-Lexicon/OneFilePerLanguage/Bosnian-NRC-Emotion-Intensity-Lexicon-v1.txt
  inflating: /Users/maximilianmaurer/Projects/elfen-tutorials/.venv/lib/python3.12/site-packages/elfen_resources/Emotion/Intensity//NRC-Emotion-Intensity-Lexicon/OneFilePerLanguage/Shona-NRC-Emotion-Intensity-Lexicon-v1.txt
  inflating: /Users/maximilianmaurer/Projects/elfen-tutorials/.venv/lib/python3.12/site-packages/elfen_resources/Emotion/Intensity//NRC-Emotion-Intensity-Lexicon/OneFilePerLanguage/Slovenian-NRC-Emotion-Intensity-Lexicon-v1.txt
  inflating: /Users/maximilianmaurer/Projects/elfen-tutorials/.venv/lib/python3.12/site-packages/elfen_resources/Emotion/Intensity//NRC-Emotion-Intensity-Lexicon/OneFilePerLanguage/Myanmar-Burmese-NRC-Emotion-Intensity-Lexicon-v1.txt

# Minimal running example

In [11]:
import elfen
import datasets
import polars as pl

In [12]:
ds = datasets.load_dataset("stanfordnlp/sst2")

In [13]:
ds = pl.from_pandas(ds["test"].to_pandas())

In [14]:
ds.head()

shape: (5, 3)
┌─────┬─────────────────────────────────┬───────┐
│ idx ┆ sentence                        ┆ label │
│ --- ┆ ---                             ┆ ---   │
│ i32 ┆ str                             ┆ i64   │
╞═════╪═════════════════════════════════╪═══════╡
│ 0   ┆ uneasy mishmash of styles and … ┆ -1    │
│ 1   ┆ this film 's relationship to a… ┆ -1    │
│ 2   ┆ by the end of no such thing th… ┆ -1    │
│ 3   ┆ director rob marshall went out… ┆ -1    │
│ 4   ┆ lathan and diggs have consider… ┆ -1    │
└─────┴─────────────────────────────────┴───────┘

Test initialization

In [15]:
extractor = elfen.Extractor(
    data=ds,
    text_column="sentence",
    language="en",
    model="en_core_web_sm",
)

Test extraction of features that do not require a lexicon

In [16]:
extractor.extract_feature_group("surface")

In [17]:
"n_tokens" in extractor.data.columns

True

Test extraction of features that require a lexicon that is automatically downloaded

In [18]:
extractor.extract("n_high_concreteness")

In [19]:
extractor.data["n_high_concreteness"].describe()

shape: (9, 2)
┌────────────┬──────────┐
│ statistic  ┆ value    │
│ ---        ┆ ---      │
│ str        ┆ f64      │
╞════════════╪══════════╡
│ count      ┆ 1821.0   │
│ null_count ┆ 0.0      │
│ mean       ┆ 3.104338 │
│ std        ┆ 2.309343 │
│ min        ┆ 0.0      │
│ 25%        ┆ 1.0      │
│ 50%        ┆ 3.0      │
│ 75%        ┆ 4.0      │
│ max        ┆ 14.0     │
└────────────┴──────────┘

Test extraction of features that require a lexicon that has to be manually added

In [23]:
extractor.extract("n_high_intensity")

In [24]:
extractor.data["n_high_intensity_joy"].describe()

shape: (9, 2)
┌────────────┬──────────┐
│ statistic  ┆ value    │
│ ---        ┆ ---      │
│ str        ┆ f64      │
╞════════════╪══════════╡
│ count      ┆ 1821.0   │
│ null_count ┆ 0.0      │
│ mean       ┆ 0.225151 │
│ std        ┆ 0.477912 │
│ min        ┆ 0.0      │
│ 25%        ┆ 0.0      │
│ 50%        ┆ 0.0      │
│ 75%        ┆ 0.0      │
│ max        ┆ 3.0      │
└────────────┴──────────┘